---
- name: update
  apt:
   update_cache: yes

- name: install mysql
  apt:
   name: mysql-server
   state: present

- name: Sets the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
