---
  - name: install jenkins using wget
    shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

  - name: append the packages
    shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

  - name: update
    apt:
     update_cache: yes

  - name: install Jenkins
    apt:
     name: Jenkins
     state: present



      